kas/kas/urls.py
from django.conf import settings
from django.urls import path

from kas.views import (  # isort: skip
    ActivatePolicyTaxYearView,
    AgreementDownloadView,
    AgterskrivelseView,
    CreateLockForYearTemplateView,
    DispatchFinalSettlement,
    EditAmountsUpdateView,
    FeatureFlagView,
    FinalSettlementDownloadView,
    FinalSettlementGenerateView,
    KasLoginView,
    LockDetailView,
    LockFilterView,
    LocksHtmxView,
    MarkFinalSettlementAsInvalid,
    NoteUpdateView,
    PdfDownloadView,
    PensionCompanyFormView,
    PensionCompanyHtmxView,
    PensionCompanySummaryFileDownloadView,
    PensionCompanySummaryFileView,
    PensionCompanyUpdateView,
    PersonNotesAndAttachmentsView,
    PersonRepresentStartView,
    PersonRepresentStopView,
    PersonTaxYearDetailView,
    PersonTaxYearDocumentsAndNotesUpdateView,
    PersonTaxYearEskatDiffListView,
    PersonTaxYearFailSendListView,
    PersonTaxYearGeneralAndForeignNotesListView,
    PersonTaxYearHistoryDetailView,
    PersonTaxYearHistoryListView,
    PersonTaxYearListView,
    PersonTaxYearUnfinishedListView,
    PersonTaxYearUnhandledDocumentsAndNotes,
    PolicyDocumentDownloadView,
    PolicyNotesAndAttachmentsView,
    PolicyPaymentOverrideView,
    PolicyTaxYearCompanyUpdateView,
    PolicyTaxYearCreateView,
    PolicyTaxYearDetailView,
    PolicyTaxYearHistoryDetailView,
    PolicyTaxYearHistoryListView,
    PolicyTaxYearNumberUpdateView,
    PolicyTaxYearTabView,
    PolicyTaxYearTaxDifferenceListView,
    PolicyTaxYearUnfinishedListView,
    PreviousYearNegativePayoutHistoryListView,
    SelfReportedAmountUpdateView,
    StatisticsView,
    UpdateEfterbehandlingView,
    UpdatePreviousYearNegativePayoutView,
    UpdateSingleMandtal,
    UploadExistingFinalSettlementView,
    WaitForSingleMandtal,
)
from kas.viewsets import (  # isort: skip
    CurrentFinalSettlementDownloadView,
    CurrentFinalSettlementExistsView,
    TokenValidationView,
)

app_name = "kas"

urlpatterns = [
    path("", PersonTaxYearListView.as_view(), name="person_search"),
    path(
        "person/unfinished/",
        PersonTaxYearUnfinishedListView.as_view(),
        name="person_search_unfinished",
    ),
    path(
        "person/failsend/",
        PersonTaxYearFailSendListView.as_view(),
        name="person_search_failsend",
    ),
    path(
        "person/unhandled/",
        PersonTaxYearUnhandledDocumentsAndNotes.as_view(),
        name="person_search_unhandled",
    ),
    path(
        "person/foreign/",
        PersonTaxYearGeneralAndForeignNotesListView.as_view(),
        name="person_search_foreign",
    ),
    path(
        "person/eskat_diff/",
        PersonTaxYearEskatDiffListView.as_view(),
        name="person_search_eskat_diff",
    ),
    path(
        "person/<int:pk>/represent/",
        PersonRepresentStartView.as_view(),
        name="person_represent_start",
    ),
    path(
        "represent-stop/",
        PersonRepresentStopView.as_view(),
        name="person_represent_stop",
    ),
    path("token/", TokenValidationView.as_view()),
    path("statistics/", StatisticsView.as_view(), name="statistics"),
    path(
        "tax_year/<int:year>/persons/<int:person_id>/",
        PersonTaxYearDetailView.as_view(),
        name="person_in_year",
    ),
    path(
        "tax_year/<int:year>/persons/<int:person_id>/pdf/",
        PdfDownloadView.as_view(),
        name="get_pdf",
    ),
    path(
        "tax_year/<int:year>/persons/<int:person_id>/policy/",
        PolicyTaxYearCreateView.as_view(),
        name="policy_create",
    ),
    path(
        "tax_year/<int:year>/persons/<int:person_id>/policies/",
        PolicyTaxYearTabView.as_view(),
        name="policy_tabs",
    ),
    path(
        "person_tax_year/<int:pk>/handled/",
        PersonTaxYearDocumentsAndNotesUpdateView.as_view(),
        name="person_in_year_handled",
    ),
    path("policy/<int:pk>/", PolicyTaxYearDetailView.as_view(), name="policy_detail"),
    path(
        "policy/<int:pk>/activate/",
        ActivatePolicyTaxYearView.as_view(),
        name="policy_activate",
    ),
    path(
        "policy/<int:pk>/company/",
        PolicyTaxYearCompanyUpdateView.as_view(),
        name="policy_company",
    ),
    path(
        "policy/<int:pk>/number/",
        PolicyTaxYearNumberUpdateView.as_view(),
        name="policy_number",
    ),
    path(
        "policy/unfinished/",
        PolicyTaxYearUnfinishedListView.as_view(),
        name="policy_search_unfinished",
    ),
    path(
        "policy/taxdifference/",
        PolicyTaxYearTaxDifferenceListView.as_view(),
        name="policy_search_taxdifference",
    ),
    path(
        "policy/<int:pk>/paymentoverride/",
        PolicyPaymentOverrideView.as_view(),
        name="policy_payment_override",
    ),
    path(
        "policy_document/<int:pk>/",
        PolicyDocumentDownloadView.as_view(),
        name="policy_document_download",
    ),
    path(
        "change/selfreportedamount/<int:pk>/",
        SelfReportedAmountUpdateView.as_view(),
        name="change-self-reported-amount",
    ),
    path(
        "change/editamounts/<int:pk>/",
        EditAmountsUpdateView.as_view(),
        name="change-edit-amounts",
    ),
    path(
        "person/<int:pk>/add/notes-attachments/",
        PersonNotesAndAttachmentsView.as_view(),
        name="person_add_notes_or_attachement",
    ),
    path(
        "policy/<int:pk>/add/notes-attachments/",
        PolicyNotesAndAttachmentsView.as_view(),
        name="policy_add_notes_or_attachement",
    ),
    path(
        "tax_year/latest/company-summary/",
        PensionCompanySummaryFileView.as_view(),
        name="policy_summary_list_latest",
    ),
    path(
        "tax_year/<int:year>/company-summary/",
        PensionCompanySummaryFileView.as_view(),
        name="policy_summary_list",
    ),
    path(
        "tax_year/<int:year>/company-summary/<int:pk>/",
        PensionCompanySummaryFileDownloadView.as_view(),
        name="policy_summary",
    ),
    path(
        "persontaxyear/<int:pk>/history/",
        PersonTaxYearHistoryListView.as_view(),
        name="person_history_list",
    ),
    path(
        "persontaxyear/history/<int:pk>/",
        PersonTaxYearHistoryDetailView.as_view(),
        name="person_history_detail",
    ),
    path(
        "policytaxyear/<int:pk>/history/",
        PolicyTaxYearHistoryListView.as_view(),
        name="policy_history_list",
    ),
    path(
        "policytaxyear/history/<int:pk>/",
        PolicyTaxYearHistoryDetailView.as_view(),
        name="policy_history_detail",
    ),
    path(
        "final_settlement/<uuid:uuid>/",
        FinalSettlementDownloadView.as_view(),
        name="final_settlement_download",
    ),
    path(
        "final_settlement/generate/<int:pk>/",
        FinalSettlementGenerateView.as_view(),
        name="generate-final-settlement",
    ),
    path(
        "final_settlement/<uuid:pk>/invalid/",
        MarkFinalSettlementAsInvalid.as_view(),
        name="invalid-final-settlement",
    ),
    path(
        "final_settlement/<uuid:pk>/dispatch/",
        DispatchFinalSettlement.as_view(),
        name="dispatch-final-settlement",
    ),
    path(
        "final_settlement/<int:year>/<str:cpr>/",
        CurrentFinalSettlementDownloadView.as_view(),
        name="current-final-settlement",
    ),
    path(
        "final_settlement/<int:year>/<str:cpr>/exists/",
        CurrentFinalSettlementExistsView.as_view(),
        name="current-final-settlement-exists",
    ),
    path(
        "final_settlement/<uuid:pk>/pseudo-update/",
        UploadExistingFinalSettlementView.as_view(),
        name="update-pseudo-final-settlement",
    ),
    path(
        "persontaxyear/<int:pk>/update_mandtal/",
        UpdateSingleMandtal.as_view(),
        name="update_persontaxyear_mandtal",
    ),
    path(
        "wait_for_mandtal_update/<uuid:pk>/",
        WaitForSingleMandtal.as_view(),
        name="wait_for_mandtal_update",
    ),
    path(
        "pensioncompany/",
        PensionCompanyFormView.as_view(),
        name="pensioncompany-listview",
    ),
    path(
        "pensioncompanyhtmx/",
        PensionCompanyHtmxView.as_view(),
        name="pensioncompany-htmxview",
    ),
    path(
        "pensioncompanyhtmx/<int:last_id>/",
        PensionCompanyHtmxView.as_view(),
        name="pensioncompany-htmxview",
    ),
    path(
        "pensioncompany/<int:pk>/edit/",
        PensionCompanyUpdateView.as_view(),
        name="pensioncompany-updateview",
    ),
    path(
        "pensioncompany/<int:pk>/agreement/",
        AgreementDownloadView.as_view(),
        name="pensioncompany-agreementdownload",
    ),
    path("lock/", LockFilterView.as_view(), name="locks"),
    path("lock/htmx/", LocksHtmxView.as_view(), name="locks-htmxview"),
    path("lock/<int:pk>/", LockDetailView.as_view(), name="lock-details"),
    path(
        "lock/<int:pk>/<str:format>/",
        LockDetailView.as_view(),
        name="lock-details",
    ),
    path("lock/create/", CreateLockForYearTemplateView.as_view(), name="lock-create"),
    path("note/<int:pk>/", NoteUpdateView.as_view(), name="note-update"),
    path(
        "agterskrivelse/<uuid:pk>/", AgterskrivelseView.as_view(), name="agterskrivelse"
    ),
    path(
        "policy/<int:pk>/negativepayoutdefined/<int:from>/<int:to>/",
        UpdatePreviousYearNegativePayoutView.as_view(),
        name="define-negative-policy-payout",
    ),
    path(
        "policy/<int:pk>/negativepayoutdefined/<int:from>/<int:to>/history/",
        PreviousYearNegativePayoutHistoryListView.as_view(),
        name="define-negative-policy-payout-history",
    ),
    path("accounts/login/", KasLoginView.as_view(), name="login"),
    path(
        "policy/<int:pk>/update_efterbehandling",
        UpdateEfterbehandlingView.as_view(),
        name="update-efterbehandling",
    ),
]

if settings.FEATURE_FLAGS.get("enable_feature_flag_list"):

kas/kas/templates/kas/lock/allow.html
{# used as a modal from the locks view to either show an error or allow the user to confirm the creation of the new lock #}
{% load i18n %}
<div id="modal-backdrop" class="modal-backdrop fade show"></div>
<div id="modal" class="modal fade show" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{% if object.get_current_lock.allow_closing %}{% translate 'Bekræft oprettelse af ny lås' %}{% else %}{% translate 'Kan ikke oprette lås' %}{% endif %}</h5>
            </div>
            <div class="modal-body">
                <p>
                {% if object.get_current_lock.allow_closing %}
                    {% translate 'Dette vil lukke den igangværende lås.' %}
                {% else %}
                    {% blocktranslate with amount=object.get_current_lock.remaining_transaction_sum %}
                        Kan ikke oprette ny lås da der mangler at blive overført {{ amount }} kr. til prisme!
                    {% endblocktranslate %}
                {% endif %}
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary">{% translate 'Luk' %}</button>
                {% if object.get_current_lock.allow_closing %}
                    <form>
                        {% csrf_token %}
                        <input type="hidden" name="taxyear" value="{{ object.pk }}"/>
                        <button hx-target="#js-locks-tr" hx-post="{% url 'kas:lock-create' %}" type="button" class="btn btn-success">{% translate 'Bekræft oprettelse' %}</button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>

kas/kas/templates/kas/lock/locks_tr.html
{# return locks as TR`s used by htmx #}
{% for lock in object_list %}
    <tr>
        <td class="text-center">{{ lock.taxyear.year }}</td>
        <td class="text-center"><a href="{% url 'kas:lock-details' lock.id %}">{% if lock.interval_to %}<i class="fa fa-lock"></i>{% else %}<i class="fa fa-lock-open"></i>{% endif %}</a></td>
        <td class="text-center"><a href="{% url 'kas:lock-details' lock.id %}">{{ lock.interval_from }}</a></td>
        <td class="text-center">{{ lock.interval_to|default_if_none:'' }}</td>
        <td class="text-center">{{ lock.settlements_count }}</td>
        <td class="text-center">{{ lock.total_tax_sum }}</td>
        <td class="text-center">{{ lock.previous_transactions_sum }}</td>
    </tr>
{% endfor %}