selvbetjening/metrics/urls.py
# SPDX-FileCopyrightText: 2023 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

from django.urls import path

from metrics.views import (  # isort: skip
    health_check_database,
    health_check_storage,
)

urlpatterns = [
    path("health/storage", health_check_storage, name="health_check_storage"),
    path("health/database", health_check_database, name="health_check_database"),
]

selvbetjening/selvbetjening/urls.py
from django.conf.urls import include
from django.urls import path
from django.views.generic import RedirectView, TemplateView
from django_mitid_auth.saml.views import AccessDeniedView

from selvbetjening.views import (  # isort: skip
    CustomJavaScriptCatalog,
    ErrorView,
    PolicyDetailPriorView,
    PolicyDetailView,
    PolicyFormView,
    RepresentationStartView,
    RepresentationStopView,
    SetLanguageView,
    ViewFinalSettlementView,
)

app_name = "selvbetjening"

urlpatterns = [
    path("", RedirectView.as_view(url="/policy/edit/")),
    path("policy/<int:year>/", PolicyDetailView.as_view(), name="policy-view"),
    path(
        "policy/prior/<int:year>/",
        PolicyDetailPriorView.as_view(),
        name="policy-prior-view",
    ),
    path("policy/edit/", PolicyFormView.as_view(), name="policy-edit"),
    path(
        "policy/submitted/",
        TemplateView.as_view(template_name="submitted.html"),
        name="policy-submitted",
    ),
    path(
        "policy/no_person_data/",
        ErrorView.as_view(template_name="not_found.html"),
        name="person-not-found",
    ),
    path(
        "language/<str:locale>/",
        CustomJavaScriptCatalog.as_view(domain="django", packages=["selvbetjening"]),
        name="javascript-language-catalog",
    ),
    path("language/", SetLanguageView.as_view(), name="set-language"),
    path(
        "policy/closed/",
        TemplateView.as_view(template_name="closed.html"),
        name="closed",
    ),
    path(
        "final_settlement/<int:year>/",
        ViewFinalSettlementView.as_view(),
        name="final-settlement",
    ),
    path(
        "represent-start/",
        RepresentationStartView.as_view(),
        name="representation-start",
    ),
    path(
        "represent-stop/", RepresentationStopView.as_view(), name="representation-stop"
    ),
    path("_ht/", include("watchman.urls")),
    path(
        "error/login-timeout/",
        AccessDeniedView.as_view(template_name="error/login_timeout.html"),
        name="login-timeout",
    ),
    path(
        "error/login-repeat/",
        AccessDeniedView.as_view(template_name="error/login_repeat.html"),
        name="login-repeat",
    ),
    path(
        "error/login-nocpr/",
        AccessDeniedView.as_view(template_name="error/login_no_cpr.html"),
        name="login-no-cpr",
    ),
    path(
        "error/login_assurance/",
        AccessDeniedView.as_view(template_name="error/login_assurance.html"),
        name="login-assurance-level",
    ),
]

selvbetjening/selvbetjening/models.py
# from django.db import models

# Create your models here.

selvbetjening/selvbetjening/views.py
import json
import logging
from datetime import date

from django.conf import settings
from django.forms import formset_factory
from django.http import FileResponse, HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.template import Context, Engine
from django.urls import reverse
from django.utils import timezone, translation
from django.utils.decorators import method_decorator
from django.utils.translation import gettext as _
from django.utils.translation.trans_real import DjangoTranslation
from django.views import View
from django.views.decorators.cache import cache_control
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView, RedirectView, TemplateView
from django.views.i18n import JavaScriptCatalog

from selvbetjening.exceptions import PersonNotFoundException
from selvbetjening.forms import PersonTaxYearForm, PolicyForm, RepresentationTokenForm
from selvbetjening.restclient import RestClient

logger = logging.getLogger(__name__)


class CustomJavaScriptCatalog(JavaScriptCatalog):
    js_catalog_template = r"""
    {% autoescape off %}
    (function(globals) {
    const django = globals.django || (globals.django = {});
    django.catalog = django.catalog || {};
    {% if catalog_str %}
    django.catalog["{{ locale }}"] = {{ catalog_str }};
    {% endif %}
    }(this));
    {% endautoescape %}
    """

    @cache_control(max_age=3600, public=True)
    def get(self, request, locale, *args, **kwargs):
        domain = kwargs.get("domain", self.domain)
        self.locale = locale
        # If packages are not provided, default to all installed packages, as
        # DjangoTranslation without localedirs harvests them all.
        packages = kwargs.get("packages", "")
        packages = packages.split("+") if packages else self.packages
        paths = self.get_paths(packages) if packages else None
        self.translation = DjangoTranslation(locale, domain=domain, localedirs=paths)
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = {"locale": self.locale}
        context.update(super(CustomJavaScriptCatalog, self).get_context_data(**kwargs))
        context["catalog_str"] = (
            json.dumps(context["catalog"], sort_keys=True, indent=2)
            if context["catalog"]
            else None
        )
        context["formats_str"] = json.dumps(
            context["formats"], sort_keys=True, indent=2
        )
        return context

    def render_to_response(self, context, **response_kwargs):
        template = Engine().from_string(self.js_catalog_template)
        return HttpResponse(
            template.render(Context(context)), 'text/javascript; charset="utf-8"'
        )


class SetLanguageView(View):
    def post(self, request, *args, **kwargs):
        language = request.POST.get("language", settings.LANGUAGE_CODE)
        translation.activate(language)
        # request.session[translation.LANGUAGE_SESSION_KEY] = language
        response = JsonResponse("OK", safe=False)
        response.set_cookie(
            settings.LANGUAGE_COOKIE_NAME,
            settings.LOCALE_MAP.get(language, language),
            domain=settings.LANGUAGE_COOKIE_DOMAIN,
            path=settings.LANGUAGE_COOKIE_PATH,
        )
        # set_cookie() doesn't let us set the SameSite property, so we do it explicitly
        response.cookies[settings.LANGUAGE_COOKIE_NAME]["SameSite"] = "Strict"
        return response


class HasUserMixin(object):
    @property
    def cpr(self):
        return self.request.session["user_info"].get("cpr")

    @property
    def name(self):
        return self.request.session["user_info"].get("personname")

    @property
    def admin_name(self):
        return self.request.session["user_info"].get("adminusername")

    def get_context_data(self, **kwargs):
        return super(HasUserMixin, self).get_context_data(
            **{
                "cpr": self.cpr,
                "cpr_x": (self.cpr[0:6] + "xxxx") if self.cpr else None,
                "name": self.name,
                "admin_name": self.admin_name,
                **kwargs,
            }
        )


class CloseMixin(object):
    def redirect_if_close_time(self):
        if (
            settings.CLOSE_AT["month"] > 0 and settings.CLOSE_AT["date"] > 0
        ):  # Test server should be able to deactivate closing
            today = timezone.now().date()
            close_date = date(
                today.year, settings.CLOSE_AT["month"], settings.CLOSE_AT["date"]
            )
            if today >= close_date:
                return redirect(
                    reverse("selvbetjening:policy-view", kwargs={"year": today.year})
                )

    def dispatch(self, request, *args, **kwargs):
        redir = self.redirect_if_close_time()
        if redir:
            return redir
        return super().dispatch(request, *args, **kwargs)


class YearTabMixin(object):
    cutoff_years = 3

    def get_context_data(self, **kwargs):
        client = RestClient()
        all_years = client.get_person_tax_years(self.cpr)
        all_years.sort(key=lambda pty: pty["tax_year"]["year"], reverse=True)
        return super().get_context_data(
            **{
                **kwargs,
                "person_tax_years": {
                    "all": all_years,
                    "latest": all_years[0 : self.cutoff_years],
                    "prior": all_years[self.cutoff_years :],
                },
                "latest_year": date.today().year - 1,
                "latest_tax_year": all_years[0]["tax_year"] if len(all_years) else None,
            }
        )


class ErrorView(HasUserMixin, TemplateView):
    pass


class PolicyFormView(HasUserMixin, CloseMixin, YearTabMixin, FormView):
    template_name = "form.html"
    success_url = ""
    form_class = formset_factory(PolicyForm, min_num=0, extra=1)

    def get(self, request, *args, **kwargs):
        try:
            self.load_initial()
        except PersonNotFoundException:
            logger.info(
                f"Attempted PolicyFormView with CPR {self.cpr},"
                + " but this CPR was not found in database"
            )
            return redirect(reverse("selvbetjening:person-not-found"))
        return super(PolicyFormView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        extra_form = self.get_extra_form()
        if form.is_valid() and extra_form.is_valid():
            return self.form_valid(form, extra_form)
        else:
            return self.form_invalid(form)

    def get_form(self, form_class=None):
        formset = super(PolicyFormView, self).get_form(form_class=form_class)
        choices = [(None, _("--- angiv navn ---"))] + [
            (company["id"], company["name"])
            for company in self.request.session["pension_companies"]
        ]
        for form in formset.extra_forms:
            form.fields["pension_company_id"].widget.choices = choices
        return formset

    def get_extra_form(self):
        kwargs = {"initial": self.request.session["person_tax_year"]}
        if self.request.method in ("POST", "PUT"):
            kwargs.update(
                {
                    "data": self.request.POST,
                    "files": self.request.FILES,
                }
            )
        return PersonTaxYearForm(**kwargs)

    def get_context_data(self, **kwargs):
        context = {
            **kwargs,
            "year": date.today().year - 1,
            "person_tax_year": self.request.session["person_tax_year"],
            "data": {
                str(item["id"]): item
                for item in self.request.session["policy_tax_years"]
            },
            "extra_form": self.get_extra_form(),
        }
        return super(PolicyFormView, self).get_context_data(**context)

    @property
    def year(self):
        return date.today().year - 2

    def load_initial(self):
        # Load known policy_tax_year data to populate form with initial data
        # We should only do this once per get-post cycle, because it contains
        # requests to the REST backend (and is thus "expensive")
        client = RestClient()
        person_tax_year = client.get_person_tax_year(self.cpr, self.year)
        if person_tax_year is not None:
            self.request.session["person_tax_year"] = person_tax_year
            policy_tax_years = client.get_policies(
                person_tax_year=person_tax_year["id"],
                active=True,
            )
            policy_tax_years.sort(key=lambda k: str(k["pension_company"]["name"]))
        else:
            raise PersonNotFoundException()
        self.request.session["policy_tax_years"] = policy_tax_years
        pension_companies = client.get_pension_companies()
        self.request.session["pension_companies"] = pension_companies

    def get_initial(self):
        return self.request.session["policy_tax_years"]

    def form_valid(self, form, extra_form):
        client = RestClient(self.request.session["user_info"])
        for policyform in form:
            policyform_data = policyform.get_nonfile_data()
            if len(policyform_data):
                id = policyform_data["id"]
                if id is None:
                    # Creating new
                    if (
                        policyform_data["pension_company_name"]
                        and not policyform_data["pension_company_id"]
                    ):
                        pension_company = client.create_pension_company(
                            policyform_data.pop("pension_company_name")
                        )
                        policyform_data["pension_company"] = pension_company["id"]
                    else:
                        policyform_data["pension_company"] = policyform_data[

selvbetjening/selvbetjening/templates/base.html
{% load static %}
{% load i18n %}
{% load kas_tags %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1,user-scalable=yes">
        <title>Sullissivik</title>
        <meta name="description" content="">
        <link rel="stylesheet" type="text/css" href="{% static 'selvbetjening/css/header_footer.css' %}" nonce="{{ request.csp_nonce }}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'selvbetjening/css/form.css' %}" nonce="{{ request.csp_nonce }}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'selvbetjening/css/main.css' %}" nonce="{{ request.csp_nonce }}"/>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous" nonce="{{ request.csp_nonce }}"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous" nonce="{{ request.csp_nonce }}">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous" nonce="{{ request.csp_nonce }}"></script>
        <script type="text/javascript" src="{% static 'selvbetjening/js/cookies.js' %}" nonce="{{ request.csp_nonce }}"></script>
        <script type="text/javascript" nonce="{{ request.csp_nonce }}">
            $.ajaxPrefilter(function (options, originalOptions, jqXHR) {
                if (!options.headers) options.headers = {};
                options.headers["X-CSRFToken"] = django.getCookie('csrftoken');
            });
        </script>
        {% block extra_headers %}{% endblock %}
    </head>
    <body>
        {% csrf_token %}
        <div class="wrapper">
            <header class="globalheader printhide">
                <div class="globalheader-wrapper">
                    <h1 class="globalheader-heading">
                        <a href="https://sullissivik.gl" data-locale-attr="href" data-locale-format="https://sullissivik.gl?sc_lang={locale}" class="router-link-exact-active router-link-active">
                            <img src="{% static 'selvbetjening/img/sullissivik_logo_gl.svg' %}" alt="Sullissivik" class="globalheader-logo">
                        </a>
                    </h1>
                    <div class="locale-changer">

                        {# Client-side language chooser, requires all ui texts to appear in data-trans attributes #}
                        {# {% if LANGUAGE_CODE|split:'-'|first == 'kl' %} #}
                        {#     <span id="locale_flag_change" class="option-da" data-language="da"></span> #}
                        {# {% else %} #}
                        {#     <span id="locale_flag_change" class="option-kl" data-language="kl"></span> #}
                        {# {% endif %} #}

                        <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                            {% if LANGUAGE_CODE|split:'-'|first == 'kl' %}
                                <button type="submit" name="language" value="da" class="option-da"></button>
                            {% else %}
                                <button type="submit" name="language" value="kl" class="option-kl"></button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </header>
            <main>
                <nav class="top-navigation">
                    <div class="userinfo">
                        {% if admin_name %}
                            {% if name %}
                            <span>{% blocktrans %}Logget ind som {{ admin_name }} på vegne af {{ name }}{% endblocktrans %}</span>
                            {% elif cpr_x %}
                            <span>{% blocktrans with cpr=cpr_x %}Logget ind som {{ admin_name }} på vegne af {{ cpr }}{% endblocktrans %}</span>
                            {% endif %}
                            <a href="{% url 'selvbetjening:representation-stop' %}">{% translate 'Afslut repræsentation' %}</a>
                        {% else %}
                            {% if name %}
                                <span>{% blocktrans %}Logget ind som {{ name }}{% endblocktrans %}</span>
                            {% elif cpr_x %}
                                <span>{% blocktrans with cpr=cpr_x %}Logget ind som {{ cpr }}{% endblocktrans %}</span>
                            {% endif %}
                            {% if cpr %}
                                {# 'login' == settings.LOGIN_NAMESPACE #}
                                <a href="{% url 'login:logout' %}" id="logout-link">{% translate 'Log ud' %}</a>
                            {% endif %}
                        {% endif %}

                    </div>
                </nav>
                {% block content %}
                {% endblock %}
            </main>
            <script nonce="{{ request.csp_nonce }}">
                $("#logout-link").on('click', function () {
                    return confirm("{% translate 'Er du sikker på at du vil logge ud?\nDet anbefales at du lukker browserfanen efter at du er logget ud' %}");
                });
            </script>
        </div>
    </body>
</html>

selvbetjening/selvbetjening/templates/calculation.html
{% load i18n %}

<h3>{% translate 'Beregning' %}</h3>
<table class="table">
    <thead>
    <tr>
        <th class="col-3-sm">{% translate 'Feltnavn' %}</th>
        <th class="col-8-sm">{% translate 'Beskrivelse' %}</th>
        <th class="col-1-sm">{% translate 'Værdi' %}</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>{% translate 'Antal skattepligtige dage i skatteår' %}</td>
        <td></td>
        <td>{{ policy.person_tax_year.number_of_days }}</td>
    </tr>
    <tr>
        <td>{% translate 'Justeringsfaktor dage i skatteår' %}</td>
        <td></td>
        <td>{{ policy.person_tax_year.days_in_year_factor }}</td>
    </tr>
    <tr>
        <td>{% translate 'Beløb justeret for skatteår' %}</td>
        <td></td>
        <td>{{ policy.year_adjusted_amount }}</td>
    </tr>
    <tr>
        <td>{% translate 'Skattegrundlag før eventuelt negativt afkast.' %}</td>
        <td></td>
        <td>{{ policy.year_adjusted_amount|max:0 }}</td>
    </tr>
    <tr>
        <td>{% translate 'Sum ikke anvendt negativt afkast' %}</td>
        <td></td>
        <td>{{ policy.available_deduction_from_previous_years }}</td>
    </tr>
    <tr>
        <td>{% translate 'Anvendt negativt afkast' %}</td>
        <td></td>
        <td>{{ policy.applied_deduction_from_previous_years }}</td>
    </tr>
    <tr>
        <td>{% translate 'Skattepligtigt beløb / skattegrundlag' %}</td>
        <td></td>
        <td>{{ policy.calculated_result }}</td>
    </tr>
    </tbody>
</table>

selvbetjening/selvbetjening/templates/closed.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="container">
    <p>{% blocktrans %}Digital indberetning af selvangivelse for dette skatteår, er ikke længere tilgængelig. Kontakt venligst Skattestyrelsen.{% endblocktrans %}</p>
</div>
{% endblock %}

selvbetjening/selvbetjening/templates/nav-tabs.html
{% load i18n %}
<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav nav-tabs navbar-nav">
                {% for person_tax_year in person_tax_years.latest %}
                {% with tabyear=person_tax_year.tax_year.year %}
                <li class="nav-item">
                    {% if year == tabyear %}
                    <a href="#" class="nav-link active">{{ tabyear }}</a>
                    {% else %}
                    <a href="{% url 'selvbetjening:policy-view' year=tabyear %}" class="nav-link">{{ tabyear }}</a>
                    {% endif %}
                </li>
                {% endwith %}
                {% endfor %}

                {% with first_prior=person_tax_years.prior|first %}
                {% if first_prior %}
                <li class="nav-item">
                    <a href="{% url 'selvbetjening:policy-prior-view' year=first_prior.tax_year.year %}" class="nav-link {% if prior %}active{% endif %}">{% blocktrans %}Tidligere skatteår{% endblocktrans %}</a>
                </li>
                {% endif %}
                {% endwith %}
            </ul>
        </div>
    </div>
</nav>

selvbetjening/selvbetjening/templates/not_found.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

<div class="container">

    <p>{% translate 'Der mangler data for denne person' %}</p>

</div>

{% endblock %}

selvbetjening/selvbetjening/templates/submitted.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

<div class="container">

    <p>{% translate 'Selvangivelse opdateret. Tryk på knappen for at åbne formularen igen' %}</p>

    <p>
        <a class="btn btn-primary" href="{% url 'selvbetjening:policy-edit' %}">{% translate 'Åbn selvangivelse' %}</a>
    </p>
</div>

{% endblock %}

selvbetjening/selvbetjening/templates/view.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

{% include "nav-tabs.html" with active=current_nav %}

<div class="container">

    {% if person_tax_years.all|length == 0 %}
    <p>{% translate 'Du er ikke kendt i systemet' %}</p>
    {% else %}

    {% if prior %}
        <div class="row mb-3">
            <label for="select_year" class="col-sm-1 p-3 col-form-label col-form-label-sm">{% translate 'Skatteår:' %}</label>
            <div class="col-sm-2">
                <select name="year" id="select_year" data-change-href="/policy/prior/{value}/" autocomplete="off">
                    {% for prior_person_tax_year in person_tax_years.prior %}
                        {% with prior_year=prior_person_tax_year.tax_year.year %}
                        <option value="{{ prior_year }}" {% if prior_year == year %} selected="selected"{% endif %}>
                            {{ prior_year }}
                        </option>
                        {% endwith %}
                    {% endfor %}
                </select>
            </div>
        </div>
    {% endif %}

    <script nonce="{{ request.csp_nonce }}">
        $("select[data-change-href]").change(function(){
            const $this = $(this);
            window.location = $this.attr("data-change-href").replaceAll("{value}", $this.val());
        });
    </script>

    {% if year == latest_year %}
        {% if latest_tax_year.year_part == 'selvangivelse' %}
            <a class="btn btn-primary" href="{% url 'selvbetjening:policy-edit' %}">{% translate 'Ret selvangivelse' %}</a>
        {% else %}
            <p>{% translate 'Der kan ikke ændres på selvangivelsen på nuværende tidspunkt' %}</p>
        {% endif %}
    {% endif %}

    {% if final_settlement_exists %}
        <a class="btn btn-primary" href="{% url 'selvbetjening:final-settlement' year=year %}">{% translate 'Hent slutopgørelse' %}</a>
    {% endif %}

    <div class="accordion" id="policies">

        {% for policy in items %}
        <div class="accordion-item">
            <h2 class="accordion-header" id="heading{{ forloop.counter }}">
                <button class="accordion-button {% if not forloop.first %}collapsed{% endif %} " type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="{% if forloop.first %}true{% else %}false{% endif %}" aria-controls="collapse{{ forloop.counter }}">
                    {{ policy.pension_company.name }}, Police nr {{ policy.policy_number }}
                </button>
            </h2>
            <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse {% if forloop.first %}show{% endif %}" aria-labelledby="heading{{ forloop.counter }}" data-bs-parent="#policies">
                <div class="accordion-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="col-7-sm">{% translate 'Feltnavn' %}</th>
                                <th class="col-3-sm">{% translate 'Antal skattepligtsdage' %}</th>
                                {% if policy.self_reported_amount %}
                                    <th class="col-3-sm">{% translate 'Selvangivet' %}</th>
                                {% else%}
                                    <th class="col-3-sm">{% translate 'Fortrykt' %}</th>
                                    <th class="col-3-sm">{% translate 'Forholdsmæssigt i skattepligtsperioden' %}</th>
                                {% endif %}
                                <th class="col-3-sm">{% translate 'Felt nr.' %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="col-7-sm">{% translate 'Kapitalafkast PBL (DK) § 53 A' %}</td>
                                <td class="col-3-sm">{{ person_tax_year.number_of_days }}</td>
                                {% if policy.self_reported_amount %}
                                    <td class="col-3-sm">{{ policy.self_reported_amount }}</td>
                                {% else %}
                                    <td class="col-3-sm">{{ policy.prefilled_amount }}</td>
                                    <td class="col-3-sm">{{ policy.year_adjusted_amount }}</td>
                                {% endif %}
                                <td class="col-3-sm">KAS-201</td>
                            </tr>

                            {% for document in policy.policy_documents %}
                            <tr>
                                {% if forloop.first %}
                                <td class="col-8-sm" rowspan="{{ policy.policy_documents|length }}">{% translate 'Dokumentation' %}</td>
                                {% endif %}
                                <td class="col-4-sm" colspan="2">{{ document.name }} | {{ document.description }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
        {% endfor %}

        <div class="accordion-item">
            <h2 class="accordion-header" id="heading_notes">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_notes" aria-expanded="false" aria-controls="collapse_notes">
                    {% translate 'Yderligere information til selvangivelsen.' %}
                </button>
            </h2>
            <div id="collapse_notes" class="accordion-collapse collapse" aria-labelledby="heading_notes">
                <div class="accordion-body">
                    {% translate 'Ingen noter' as no_notes %}
                    <p>{{ person_tax_year.foreign_pension_notes|default:no_notes }}</p>
                </div>
            </div>
        </div>

        <div class="accordion-item">
            <h2 class="accordion-header" id="heading_foreign">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_foreign" aria-expanded="false" aria-controls="collapse_foreign">
                    {% translate 'Indbetaling til private pensionsordninger i andre lande.' %}
                </button>
            </h2>
            <div id="collapse_foreign" class="accordion-collapse collapse" aria-labelledby="heading_foreign">
                <div class="accordion-body">
                    {% translate 'Ingen noter' as no_notes %}
                    <p>{{ person_tax_year.general_notes|default:no_notes }}</p>
                </div>
            </div>
        </div>

        <div class="accordion-item">
            <h2 class="accordion-header" id="heading_summary">
                <button class="accordion-button {% if not forloop.first %}collapsed{% endif %} " type="button" data-bs-toggle="collapse" data-bs-target="#collapse_summary" aria-expanded="{% if forloop.first %}true{% else %}false{% endif %}" aria-controls="collapse_summary">
                    {% translate 'Opsummering' %}
                </button>
            </h2>
            <div id="collapse_summary" class="accordion-collapse collapse {% if forloop.first %}show{% endif %}" aria-labelledby="heading_summary" data-bs-parent="#policies">
                <div class="accordion-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th class="col-8-sm">{% translate 'Feltnavn' %}</th>
                            <th class="col-3-sm">{% translate 'Værdi' %}</th>
                            <th class="col-1-sm">{% translate 'Felt nr.' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td class="col-8-sm">{% translate 'Kapitalafkast PBL (DK) § 53 A' %}</td>
                            <td class="col-3-sm">{{ summary.self_reported_amount|default:summary.prefilled_adjusted_amount }}</td>
                            <td class="col-1-sm">KAS-201</td>
                        </tr>
                        <tr>
                            <td class="col-8-sm">{% translate 'Forudbetalt kapitalafkastskat' %}</td>
                            <td class="col-3-sm">{{ summary.preliminary_paid_amount|default:0 }}</td>
                            <td class="col-1-sm">KAS-205</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    {% endif %}
</div>
{% endblock %}