kas/kas/urls.py
from django.conf import settings
from django.urls import path

from kas.views import (  # isort: skip
    ActivatePolicyTaxYearView,
    AgreementDownloadView,
    AgterskrivelseView,
    CreateLockForYearTemplateView,
    DispatchFinalSettlement,
    EditAmountsUpdateView,
    FeatureFlagView,
    FinalSettlementDownloadView,
    FinalSettlementGenerateView,
    KasLoginView,
    LockDetailView,
    LockFilterView,
    LocksHtmxView,
    MarkFinalSettlementAsInvalid,
    NoteUpdateView,
    PdfDownloadView,
    PensionCompanyFormView,
    PensionCompanyHtmxView,
    PensionCompanySummaryFileDownloadView,
    PensionCompanySummaryFileView,
    PensionCompanyUpdateView,
    PersonNotesAndAttachmentsView,
    PersonRepresentStartView,
    PersonRepresentStopView,
    PersonTaxYearDetailView,
    PersonTaxYearDocumentsAndNotesUpdateView,
    PersonTaxYearEskatDiffListView,
    PersonTaxYearFailSendListView,
    PersonTaxYearGeneralAndForeignNotesListView,
    PersonTaxYearHistoryDetailView,
    PersonTaxYearHistoryListView,
    PersonTaxYearListView,
    PersonTaxYearUnfinishedListView,
    PersonTaxYearUnhandledDocumentsAndNotes,
    PolicyDocumentDownloadView,
    PolicyNotesAndAttachmentsView,
    PolicyPaymentOverrideView,
    PolicyTaxYearCompanyUpdateView,
    PolicyTaxYearCreateView,
    PolicyTaxYearDetailView,
    PolicyTaxYearHistoryDetailView,
    PolicyTaxYearHistoryListView,
    PolicyTaxYearNumberUpdateView,
    PolicyTaxYearTabView,
    PolicyTaxYearTaxDifferenceListView,
    PolicyTaxYearUnfinishedListView,
    PreviousYearNegativePayoutHistoryListView,
    SelfReportedAmountUpdateView,
    StatisticsView,
    UpdateEfterbehandlingView,
    UpdatePreviousYearNegativePayoutView,
    UpdateSingleMandtal,
    UploadExistingFinalSettlementView,
    WaitForSingleMandtal,
)
from kas.viewsets import (  # isort: skip
    CurrentFinalSettlementDownloadView,
    CurrentFinalSettlementExistsView,
    TokenValidationView,
)

app_name = "kas"

urlpatterns = [
    path("", PersonTaxYearListView.as_view(), name="person_search"),
    path(
        "person/unfinished/",
        PersonTaxYearUnfinishedListView.as_view(),
        name="person_search_unfinished",
    ),
    path(
        "person/failsend/",
        PersonTaxYearFailSendListView.as_view(),
        name="person_search_failsend",
    ),
    path(
        "person/unhandled/",
        PersonTaxYearUnhandledDocumentsAndNotes.as_view(),
        name="person_search_unhandled",
    ),
    path(
        "person/foreign/",
        PersonTaxYearGeneralAndForeignNotesListView.as_view(),
        name="person_search_foreign",
    ),
    path(
        "person/eskat_diff/",
        PersonTaxYearEskatDiffListView.as_view(),
        name="person_search_eskat_diff",
    ),
    path(
        "person/<int:pk>/represent/",
        PersonRepresentStartView.as_view(),
        name="person_represent_start",
    ),
    path(
        "represent-stop/",
        PersonRepresentStopView.as_view(),
        name="person_represent_stop",
    ),
    path("token/", TokenValidationView.as_view()),
    path("statistics/", StatisticsView.as_view(), name="statistics"),
    path(
        "tax_year/<int:year>/persons/<int:person_id>/",
        PersonTaxYearDetailView.as_view(),
        name="person_in_year",
    ),
    path(
        "tax_year/<int:year>/persons/<int:person_id>/pdf/",
        PdfDownloadView.as_view(),
        name="get_pdf",
    ),
    path(
        "tax_year/<int:year>/persons/<int:person_id>/policy/",
        PolicyTaxYearCreateView.as_view(),
        name="policy_create",
    ),
    path(
        "tax_year/<int:year>/persons/<int:person_id>/policies/",
        PolicyTaxYearTabView.as_view(),
        name="policy_tabs",
    ),
    path(
        "person_tax_year/<int:pk>/handled/",
        PersonTaxYearDocumentsAndNotesUpdateView.as_view(),
        name="person_in_year_handled",
    ),
    path("policy/<int:pk>/", PolicyTaxYearDetailView.as_view(), name="policy_detail"),
    path(
        "policy/<int:pk>/activate/",
        ActivatePolicyTaxYearView.as_view(),
        name="policy_activate",
    ),
    path(
        "policy/<int:pk>/company/",
        PolicyTaxYearCompanyUpdateView.as_view(),
        name="policy_company",
    ),
    path(
        "policy/<int:pk>/number/",
        PolicyTaxYearNumberUpdateView.as_view(),
        name="policy_number",
    ),
    path(
        "policy/unfinished/",
        PolicyTaxYearUnfinishedListView.as_view(),
        name="policy_search_unfinished",
    ),
    path(
        "policy/taxdifference/",
        PolicyTaxYearTaxDifferenceListView.as_view(),
        name="policy_search_taxdifference",
    ),
    path(
        "policy/<int:pk>/paymentoverride/",
        PolicyPaymentOverrideView.as_view(),
        name="policy_payment_override",
    ),
    path(
        "policy_document/<int:pk>/",
        PolicyDocumentDownloadView.as_view(),
        name="policy_document_download",
    ),
    path(
        "change/selfreportedamount/<int:pk>/",
        SelfReportedAmountUpdateView.as_view(),
        name="change-self-reported-amount",
    ),
    path(
        "change/editamounts/<int:pk>/",
        EditAmountsUpdateView.as_view(),
        name="change-edit-amounts",
    ),
    path(
        "person/<int:pk>/add/notes-attachments/",
        PersonNotesAndAttachmentsView.as_view(),
        name="person_add_notes_or_attachement",
    ),
    path(
        "policy/<int:pk>/add/notes-attachments/",
        PolicyNotesAndAttachmentsView.as_view(),
        name="policy_add_notes_or_attachement",
    ),
    path(
        "tax_year/latest/company-summary/",
        PensionCompanySummaryFileView.as_view(),
        name="policy_summary_list_latest",
    ),
    path(
        "tax_year/<int:year>/company-summary/",
        PensionCompanySummaryFileView.as_view(),
        name="policy_summary_list",
    ),
    path(
        "tax_year/<int:year>/company-summary/<int:pk>/",
        PensionCompanySummaryFileDownloadView.as_view(),
        name="policy_summary",
    ),
    path(
        "persontaxyear/<int:pk>/history/",
        PersonTaxYearHistoryListView.as_view(),
        name="person_history_list",
    ),
    path(
        "persontaxyear/history/<int:pk>/",
        PersonTaxYearHistoryDetailView.as_view(),
        name="person_history_detail",
    ),
    path(
        "policytaxyear/<int:pk>/history/",
        PolicyTaxYearHistoryListView.as_view(),
        name="policy_history_list",
    ),
    path(
        "policytaxyear/history/<int:pk>/",
        PolicyTaxYearHistoryDetailView.as_view(),
        name="policy_history_detail",
    ),
    path(
        "final_settlement/<uuid:uuid>/",
        FinalSettlementDownloadView.as_view(),
        name="final_settlement_download",
    ),
    path(
        "final_settlement/generate/<int:pk>/",
        FinalSettlementGenerateView.as_view(),
        name="generate-final-settlement",
    ),
    path(
        "final_settlement/<uuid:pk>/invalid/",
        MarkFinalSettlementAsInvalid.as_view(),
        name="invalid-final-settlement",
    ),
    path(
        "final_settlement/<uuid:pk>/dispatch/",
        DispatchFinalSettlement.as_view(),
        name="dispatch-final-settlement",
    ),
    path(
        "final_settlement/<int:year>/<str:cpr>/",
        CurrentFinalSettlementDownloadView.as_view(),
        name="current-final-settlement",
    ),
    path(
        "final_settlement/<int:year>/<str:cpr>/exists/",
        CurrentFinalSettlementExistsView.as_view(),
        name="current-final-settlement-exists",
    ),
    path(
        "final_settlement/<uuid:pk>/pseudo-update/",
        UploadExistingFinalSettlementView.as_view(),
        name="update-pseudo-final-settlement",
    ),
    path(
        "persontaxyear/<int:pk>/update_mandtal/",
        UpdateSingleMandtal.as_view(),
        name="update_persontaxyear_mandtal",
    ),
    path(
        "wait_for_mandtal_update/<uuid:pk>/",
        WaitForSingleMandtal.as_view(),
        name="wait_for_mandtal_update",
    ),
    path(
        "pensioncompany/",
        PensionCompanyFormView.as_view(),
        name="pensioncompany-listview",
    ),
    path(
        "pensioncompanyhtmx/",
        PensionCompanyHtmxView.as_view(),
        name="pensioncompany-htmxview",
    ),
    path(
        "pensioncompanyhtmx/<int:last_id>/",
        PensionCompanyHtmxView.as_view(),
        name="pensioncompany-htmxview",
    ),
    path(
        "pensioncompany/<int:pk>/edit/",
        PensionCompanyUpdateView.as_view(),
        name="pensioncompany-updateview",
    ),
    path(
        "pensioncompany/<int:pk>/agreement/",
        AgreementDownloadView.as_view(),
        name="pensioncompany-agreementdownload",
    ),
    path("lock/", LockFilterView.as_view(), name="locks"),
    path("lock/htmx/", LocksHtmxView.as_view(), name="locks-htmxview"),
    path("lock/<int:pk>/", LockDetailView.as_view(), name="lock-details"),
    path(
        "lock/<int:pk>/<str:format>/",
        LockDetailView.as_view(),
        name="lock-details",
    ),
    path("lock/create/", CreateLockForYearTemplateView.as_view(), name="lock-create"),
    path("note/<int:pk>/", NoteUpdateView.as_view(), name="note-update"),
    path(
        "agterskrivelse/<uuid:pk>/", AgterskrivelseView.as_view(), name="agterskrivelse"
    ),
    path(
        "policy/<int:pk>/negativepayoutdefined/<int:from>/<int:to>/",
        UpdatePreviousYearNegativePayoutView.as_view(),
        name="define-negative-policy-payout",
    ),
    path(
        "policy/<int:pk>/negativepayoutdefined/<int:from>/<int:to>/history/",
        PreviousYearNegativePayoutHistoryListView.as_view(),
        name="define-negative-policy-payout-history",
    ),
    path("accounts/login/", KasLoginView.as_view(), name="login"),
    path(
        "policy/<int:pk>/update_efterbehandling",
        UpdateEfterbehandlingView.as_view(),
        name="update-efterbehandling",
    ),
]

if settings.FEATURE_FLAGS.get("enable_feature_flag_list"):

kas/worker/urls.py
from django.urls import path

from worker.views import (  # isort: skip
    JobDetailView,
    JobListHtmxView,
    JobListTemplateView,
    JobTypeSelectFormView,
    StartJobView,
)

urlpatterns = [
    path("jobs/", JobListTemplateView.as_view(), name="job_list"),
    path("job/<uuid:uuid>/", JobDetailView.as_view(), name="job_detail"),
    # htmx views
    path("joblist/", JobListHtmxView.as_view(), name="joblist_htmx"),
    path("joblist/<uuid:last_uuid>/", JobListHtmxView.as_view(), name="joblist_htmx"),
    path("jobtypeselect/", JobTypeSelectFormView.as_view(), name="job_type_select"),
    path("jobstart/<str:job_type>/", StartJobView.as_view(), name="job_start"),
]
app_name = "worker"

kas/worker/views.py
from itertools import islice

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
from django.forms import FileField
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import FormView
from project.view_mixins import administrator_required
from worker.forms import JobTypeSelectForm
from worker.job_registry import get_job_types, resolve_job_function
from worker.models import Job

from kas.view_mixins import KasMixin


class JobListHtmxView(KasMixin, PermissionRequiredMixin, ListView):
    permission_denied_message = administrator_required
    template_name = "worker/htmx/jobs.html"
    permission_required = "worker.view_job"

    def get_queryset(self):
        chunk_size = 10
        last_uuid = self.kwargs.get("last_uuid")
        qs = Job.objects.filter(parent__isnull=True)
        if last_uuid:
            # if you provide a nonexisting uuid you get a 404
            last_object = get_object_or_404(Job, uuid=last_uuid)

            # For some reason this doesn't work completely,
            # it outputs Jobs that are later than last_object,
            # when objects are less than one second apart
            qs = qs.filter(created_at__lt=last_object.created_at).order_by(
                "-created_at"
            )

            # Do further filtering
            return islice(
                filter(
                    lambda job: job.created_at < last_object.created_at, qs.iterator()
                ),
                chunk_size,
            )

        return qs.order_by("-created_at")[:chunk_size]

    def get_context_data(self, **kwargs):
        return super().get_context_data(
            **{**kwargs, "csp_nonce": self.request.GET.get("csp_nonce")}
        )


class JobListTemplateView(KasMixin, PermissionRequiredMixin, TemplateView):
    permission_denied_message = administrator_required
    template_name = "worker/job_list.html"
    permission_required = "worker.view_job"


class JobDetailView(KasMixin, PermissionRequiredMixin, DetailView):
    permission_denied_message = administrator_required
    slug_field = "uuid"
    slug_url_kwarg = "uuid"
    model = Job
    permission_required = "worker.view_job"


class JobTypeSelectFormView(KasMixin, PermissionRequiredMixin, FormView):
    permission_denied_message = administrator_required
    template_name = "worker/job_type_select.html"
    form_class = JobTypeSelectForm
    permission_required = "worker.add_job"

    def form_valid(self, form):
        return HttpResponseRedirect(
            reverse(
                "worker:job_start", kwargs={"job_type": form.cleaned_data["job_type"]}
            )
        )


class StartJobView(KasMixin, PermissionRequiredMixin, FormView):
    permission_denied_message = administrator_required
    template_name = "worker/job_create_form.html"
    permission_required = "worker.add_job"

    def job_data(self):
        return get_job_types()[self.kwargs["job_type"]]

    def get_context_data(self, **kwargs):
        ctx = super(StartJobView, self).get_context_data(**kwargs)
        ctx.update(
            {"job_data": self.job_data(), "pretty_job_title": self.job_data()["label"]}
        )
        return ctx

    def get_form_class(self):
        try:
            return self.job_data()["form_class"]
        except IndexError:
            raise Http404("No such job type")

    def form_valid(self, form):
        # Todo: Raise a validation error if something goes wrong here?
        function_string = self.job_data().get("function", None)
        function = resolve_job_function(function_string)

        if function:
            job_kwargs = form.cleaned_data
            if FileField in [field.__class__ for field in form.fields.values()]:
                # we need to store the upload file in the file field
                # since we can't json-serialize it
                instance = form.save(commit=False)
                instance.uploaded_by = self.request.user
                instance.save()
                # Remove InMemoryUploadedFile instances from job_kwargs;
                # they have been saved to `instance`, which we refer by pk
                job_kwargs = dict(
                    filter(
                        lambda kvp: not isinstance(kvp[1], InMemoryUploadedFile),
                        job_kwargs.items(),
                    )
                )
                job_kwargs["pk"] = str(instance.pk)
            for key, value in form.cleaned_data.items():
                if isinstance(value, models.Model):
                    job_kwargs[key] = value.pk

            Job.schedule_job(
                function=function,
                job_type=self.kwargs["job_type"],
                created_by=self.request.user,
                job_kwargs=job_kwargs,
            )
        return super(StartJobView, self).form_valid(form)

    def get_success_url(self):
        return reverse("worker:job_list")

kas/worker/templates/worker/job_create_form.html
{% extends 'kas/layout.html' %}
{% load i18n %}
{% block content %}
    <h1>{{ pretty_job_title }}</h1>
    <form method="POST" class="form-inline needs-validation" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-row">
                {% if 'custom-file-input' in field.field.widget.attrs.class %}
                {# special DOM for file inputs #}
                <div class="col custom-file">
                    {{ form.file }}
                    <label class="custom-file-label" for="{{ form.file.id_for_label }}">{% translate 'Vælg en fil' %}</label>
                </div>
                <script nonce="{{ request.csp_nonce }}">
                    $(".custom-file-input").on("change", function() {
                        var fileName = $(this).val().split("\\").pop();
                        $(this).siblings(".custom-file-label").addClass("selected").text(fileName);
                    });
                </script>
                {% else %}
                <div class="col">
                    <label class="mr-2">{{ field.label }}</label>{{ field }}
                    {% if field.errors %}
                        <small class="invalid-feedback">
                            {% for error in field.errors %}
                                {{ error }}
                            {% endfor %}
                        </small>
                    {% else %}
                        <small class="form-text text-muted ml-2">{{ field.help_text }}.</small>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        {% endfor %}
        <input class="form-control btn btn-success" type="submit" value="{% translate 'Start job' %}">
        <a class="btn btn-primary btn-danger" href="{% url 'worker:job_list' %}" role="button">{% translate 'Annullér'%}</a>
    </form>
{% endblock %}

kas/worker/templates/worker/job_detail.html
{% extends 'kas/layout.html' %}

{% load i18n %}
{% load kas_worker_tags %}
{% block content %}

<a class="btn btn-primary" href="{% url 'worker:job_list' %}">{% translate 'Tilbage til liste' %}</a>

<table class="table">
    <tbody>
    <tr>
        <th>{% translate 'Type' %}</th>
        <td>{{ object.job_type }}</td>
    </tr>
    <tr>
        <th>{% translate 'Status' %}</th>
        <td><span class="btn {{ object.bootstrap_color }}">{{ object.get_status_display }}</span></td>
    </tr>
    {% if object.started_at is not None %}
    <tr>
        <th>{% translate 'Starttid' %}</th>
        <td>{{ object.started_at }}</td>
    </tr>
    {% endif %}
    {% if object.duration is not None %}
    <tr>
        <th>{% translate 'Kørselstid' %}</th>
        <td>{{ object.duration|duration }}</td>
    </tr>
    {% endif %}
    {% if object.status == 'failed' %}
        <tr>
            <th>{% translate 'Fejl' %}</th>
            <td>
                {{ object.traceback }}
            </td>
        </tr>

    {% endif %}
    {% if object.status == 'finished' or object.status == 'failed' %}
    <tr>
        <th>{% translate 'Opsummering' %}</th>
        <td class="job-summary">
            {% if object.job_type_dict.result_template %}
                {% include object.job_type_dict.result_template with result=object.result %}
            {% endif %}
        </td>
    </tr>
    {% elif object.status == 'started' %}
    <tr>
        <th>{% translate 'Fremskridt' %}</th>
        <td>{{ object.pretty_progress }}</td>
    </tr>
    {% endif %}
    </tbody>
</table>
{% endblock %}

kas/worker/templates/worker/job_list.html
{% extends 'kas/layout.html' %}
{% load static %}
{% load i18n %}
{% block content %}
    <a class="btn btn-success" href="{% url 'worker:job_type_select' %}">{% translate 'Start nyt job' %}</a>

    {% get_current_language as language_code %}
    {% if language_code == 'kl-GL' %}
        {% static 'kas/doc/kl/Manual for system til skat af visse kapitalafkast (KAS).pdf' as manual_url %}
    {% else %}
        {% static 'kas/doc/da/Manual for system til skat af visse kapitalafkast (KAS).pdf' as manual_url %}
    {% endif %}

    {% blocktrans with link=manual_url asvar help_text_jobs %}På denne side oplistes kørende og kørte jobs, med relevant information om hvert job.
        Med knappen "Start nyt job" kan der påbegyndes en ny jobkørsel, som foretager en længerevarende operation på de data der ligger i systemet, som f.eks. autoligning eller oprettelse af selvangivelser.
        Yderligere information kan findes i <a href="{{link}}">Overbliksmanualen</a>{% endblocktrans %}
    {% include 'includes/help_text/question_mark.html' with target_id='help' %}
    {% include 'includes/help_text/collapse.html' with target_id='help' help_text=help_text_jobs %}

    <table class="table table-striped mt-4">
        <thead>
            <tr>
                <th>{% translate 'Job type' %}</th>
                <th>{% translate 'Oprettet af' %}</th>
                <th>{% translate 'Oprettet' %}</th>
                <th>{% translate 'Fremskridt' %}</th>
                <th>{% translate 'Status' %}</th>
            </tr>
        </thead>
        <tbody hx-get="{% url 'worker:joblist_htmx' %}?csp_nonce={{request.csp_nonce}}" hx-trigger="load"/>
    </table>
{% endblock %}

kas/worker/templates/worker/job_type_select.html
{% extends 'kas/layout.html' %}
{% load i18n %}
{% block content %}
    <form method="POST" class="form-inline needs-validation">
        {% csrf_token %}
        {{ form }}
        <input class="btn btn-success" type="submit" value="{% translate 'Vælg' %}">
        {% include 'includes/help_text/question_mark.html' with target_id='help' %}
    </form>

    {% blocktrans asvar help_text_jobs %}
    På denne side kan der vælges hvilket type job der skal køres.
    Når der er valgt en jobtype, skal der efterfølgende vælges parametre til jobbet, f.eks. hvilket skatteår der skal behandles data for.
    {% endblocktrans %}
    {% include 'includes/help_text/collapse.html' with target_id='help' help_text=help_text_jobs %}

{% endblock %}