kas/kas/urls.py
from django.conf import settings
from django.urls import path

from kas.views import (  # isort: skip
    ActivatePolicyTaxYearView,
    AgreementDownloadView,
    AgterskrivelseView,
    CreateLockForYearTemplateView,
    DispatchFinalSettlement,
    EditAmountsUpdateView,
    FeatureFlagView,
    FinalSettlementDownloadView,
    FinalSettlementGenerateView,
    KasLoginView,
    LockDetailView,
    LockFilterView,
    LocksHtmxView,
    MarkFinalSettlementAsInvalid,
    NoteUpdateView,
    PdfDownloadView,
    PensionCompanyFormView,
    PensionCompanyHtmxView,
    PensionCompanySummaryFileDownloadView,
    PensionCompanySummaryFileView,
    PensionCompanyUpdateView,
    PersonNotesAndAttachmentsView,
    PersonRepresentStartView,
    PersonRepresentStopView,
    PersonTaxYearDetailView,
    PersonTaxYearDocumentsAndNotesUpdateView,
    PersonTaxYearEskatDiffListView,
    PersonTaxYearFailSendListView,
    PersonTaxYearGeneralAndForeignNotesListView,
    PersonTaxYearHistoryDetailView,
    PersonTaxYearHistoryListView,
    PersonTaxYearListView,
    PersonTaxYearUnfinishedListView,
    PersonTaxYearUnhandledDocumentsAndNotes,
    PolicyDocumentDownloadView,
    PolicyNotesAndAttachmentsView,
    PolicyPaymentOverrideView,
    PolicyTaxYearCompanyUpdateView,
    PolicyTaxYearCreateView,
    PolicyTaxYearDetailView,
    PolicyTaxYearHistoryDetailView,
    PolicyTaxYearHistoryListView,
    PolicyTaxYearNumberUpdateView,
    PolicyTaxYearTabView,
    PolicyTaxYearTaxDifferenceListView,
    PolicyTaxYearUnfinishedListView,
    PreviousYearNegativePayoutHistoryListView,
    SelfReportedAmountUpdateView,
    StatisticsView,
    UpdateEfterbehandlingView,
    UpdatePreviousYearNegativePayoutView,
    UpdateSingleMandtal,
    UploadExistingFinalSettlementView,
    WaitForSingleMandtal,
)
from kas.viewsets import (  # isort: skip
    CurrentFinalSettlementDownloadView,
    CurrentFinalSettlementExistsView,
    TokenValidationView,
)

app_name = "kas"

urlpatterns = [
    path("", PersonTaxYearListView.as_view(), name="person_search"),
    path(
        "person/unfinished/",
        PersonTaxYearUnfinishedListView.as_view(),
        name="person_search_unfinished",
    ),
    path(
        "person/failsend/",
        PersonTaxYearFailSendListView.as_view(),
        name="person_search_failsend",
    ),
    path(
        "person/unhandled/",
        PersonTaxYearUnhandledDocumentsAndNotes.as_view(),
        name="person_search_unhandled",
    ),
    path(
        "person/foreign/",
        PersonTaxYearGeneralAndForeignNotesListView.as_view(),
        name="person_search_foreign",
    ),
    path(
        "person/eskat_diff/",
        PersonTaxYearEskatDiffListView.as_view(),
        name="person_search_eskat_diff",
    ),
    path(
        "person/<int:pk>/represent/",
        PersonRepresentStartView.as_view(),
        name="person_represent_start",
    ),
    path(
        "represent-stop/",
        PersonRepresentStopView.as_view(),
        name="person_represent_stop",
    ),
    path("token/", TokenValidationView.as_view()),
    path("statistics/", StatisticsView.as_view(), name="statistics"),
    path(
        "tax_year/<int:year>/persons/<int:person_id>/",
        PersonTaxYearDetailView.as_view(),
        name="person_in_year",
    ),
    path(
        "tax_year/<int:year>/persons/<int:person_id>/pdf/",
        PdfDownloadView.as_view(),
        name="get_pdf",
    ),
    path(
        "tax_year/<int:year>/persons/<int:person_id>/policy/",
        PolicyTaxYearCreateView.as_view(),
        name="policy_create",
    ),
    path(
        "tax_year/<int:year>/persons/<int:person_id>/policies/",
        PolicyTaxYearTabView.as_view(),
        name="policy_tabs",
    ),
    path(
        "person_tax_year/<int:pk>/handled/",
        PersonTaxYearDocumentsAndNotesUpdateView.as_view(),
        name="person_in_year_handled",
    ),
    path("policy/<int:pk>/", PolicyTaxYearDetailView.as_view(), name="policy_detail"),
    path(
        "policy/<int:pk>/activate/",
        ActivatePolicyTaxYearView.as_view(),
        name="policy_activate",
    ),
    path(
        "policy/<int:pk>/company/",
        PolicyTaxYearCompanyUpdateView.as_view(),
        name="policy_company",
    ),
    path(
        "policy/<int:pk>/number/",
        PolicyTaxYearNumberUpdateView.as_view(),
        name="policy_number",
    ),
    path(
        "policy/unfinished/",
        PolicyTaxYearUnfinishedListView.as_view(),
        name="policy_search_unfinished",
    ),
    path(
        "policy/taxdifference/",
        PolicyTaxYearTaxDifferenceListView.as_view(),
        name="policy_search_taxdifference",
    ),
    path(
        "policy/<int:pk>/paymentoverride/",
        PolicyPaymentOverrideView.as_view(),
        name="policy_payment_override",
    ),
    path(
        "policy_document/<int:pk>/",
        PolicyDocumentDownloadView.as_view(),
        name="policy_document_download",
    ),
    path(
        "change/selfreportedamount/<int:pk>/",
        SelfReportedAmountUpdateView.as_view(),
        name="change-self-reported-amount",
    ),
    path(
        "change/editamounts/<int:pk>/",
        EditAmountsUpdateView.as_view(),
        name="change-edit-amounts",
    ),
    path(
        "person/<int:pk>/add/notes-attachments/",
        PersonNotesAndAttachmentsView.as_view(),
        name="person_add_notes_or_attachement",
    ),
    path(
        "policy/<int:pk>/add/notes-attachments/",
        PolicyNotesAndAttachmentsView.as_view(),
        name="policy_add_notes_or_attachement",
    ),
    path(
        "tax_year/latest/company-summary/",
        PensionCompanySummaryFileView.as_view(),
        name="policy_summary_list_latest",
    ),
    path(
        "tax_year/<int:year>/company-summary/",
        PensionCompanySummaryFileView.as_view(),
        name="policy_summary_list",
    ),
    path(
        "tax_year/<int:year>/company-summary/<int:pk>/",
        PensionCompanySummaryFileDownloadView.as_view(),
        name="policy_summary",
    ),
    path(
        "persontaxyear/<int:pk>/history/",
        PersonTaxYearHistoryListView.as_view(),
        name="person_history_list",
    ),
    path(
        "persontaxyear/history/<int:pk>/",
        PersonTaxYearHistoryDetailView.as_view(),
        name="person_history_detail",
    ),
    path(
        "policytaxyear/<int:pk>/history/",
        PolicyTaxYearHistoryListView.as_view(),
        name="policy_history_list",
    ),
    path(
        "policytaxyear/history/<int:pk>/",
        PolicyTaxYearHistoryDetailView.as_view(),
        name="policy_history_detail",
    ),
    path(
        "final_settlement/<uuid:uuid>/",
        FinalSettlementDownloadView.as_view(),
        name="final_settlement_download",
    ),
    path(
        "final_settlement/generate/<int:pk>/",
        FinalSettlementGenerateView.as_view(),
        name="generate-final-settlement",
    ),
    path(
        "final_settlement/<uuid:pk>/invalid/",
        MarkFinalSettlementAsInvalid.as_view(),
        name="invalid-final-settlement",
    ),
    path(
        "final_settlement/<uuid:pk>/dispatch/",
        DispatchFinalSettlement.as_view(),
        name="dispatch-final-settlement",
    ),
    path(
        "final_settlement/<int:year>/<str:cpr>/",
        CurrentFinalSettlementDownloadView.as_view(),
        name="current-final-settlement",
    ),
    path(
        "final_settlement/<int:year>/<str:cpr>/exists/",
        CurrentFinalSettlementExistsView.as_view(),
        name="current-final-settlement-exists",
    ),
    path(
        "final_settlement/<uuid:pk>/pseudo-update/",
        UploadExistingFinalSettlementView.as_view(),
        name="update-pseudo-final-settlement",
    ),
    path(
        "persontaxyear/<int:pk>/update_mandtal/",
        UpdateSingleMandtal.as_view(),
        name="update_persontaxyear_mandtal",
    ),
    path(
        "wait_for_mandtal_update/<uuid:pk>/",
        WaitForSingleMandtal.as_view(),
        name="wait_for_mandtal_update",
    ),
    path(
        "pensioncompany/",
        PensionCompanyFormView.as_view(),
        name="pensioncompany-listview",
    ),
    path(
        "pensioncompanyhtmx/",
        PensionCompanyHtmxView.as_view(),
        name="pensioncompany-htmxview",
    ),
    path(
        "pensioncompanyhtmx/<int:last_id>/",
        PensionCompanyHtmxView.as_view(),
        name="pensioncompany-htmxview",
    ),
    path(
        "pensioncompany/<int:pk>/edit/",
        PensionCompanyUpdateView.as_view(),
        name="pensioncompany-updateview",
    ),
    path(
        "pensioncompany/<int:pk>/agreement/",
        AgreementDownloadView.as_view(),
        name="pensioncompany-agreementdownload",
    ),
    path("lock/", LockFilterView.as_view(), name="locks"),
    path("lock/htmx/", LocksHtmxView.as_view(), name="locks-htmxview"),
    path("lock/<int:pk>/", LockDetailView.as_view(), name="lock-details"),
    path(
        "lock/<int:pk>/<str:format>/",
        LockDetailView.as_view(),
        name="lock-details",
    ),
    path("lock/create/", CreateLockForYearTemplateView.as_view(), name="lock-create"),
    path("note/<int:pk>/", NoteUpdateView.as_view(), name="note-update"),
    path(
        "agterskrivelse/<uuid:pk>/", AgterskrivelseView.as_view(), name="agterskrivelse"
    ),
    path(
        "policy/<int:pk>/negativepayoutdefined/<int:from>/<int:to>/",
        UpdatePreviousYearNegativePayoutView.as_view(),
        name="define-negative-policy-payout",
    ),
    path(
        "policy/<int:pk>/negativepayoutdefined/<int:from>/<int:to>/history/",
        PreviousYearNegativePayoutHistoryListView.as_view(),
        name="define-negative-policy-payout-history",
    ),
    path("accounts/login/", KasLoginView.as_view(), name="login"),
    path(
        "policy/<int:pk>/update_efterbehandling",
        UpdateEfterbehandlingView.as_view(),
        name="update-efterbehandling",
    ),
]

if settings.FEATURE_FLAGS.get("enable_feature_flag_list"):

kas/prisme/urls.py
from django.urls import path

from prisme.views import (  # isort: skip
    Prisme10QBatchDownloadView,
    Prisme10QBatchListView,
    Prisme10QBatchSendView,
    Prisme10QBatchView,
)

app_name = "prisme"

urlpatterns = [
    path("batch/", Prisme10QBatchListView.as_view(), name="batch-list"),
    path("batch/<int:pk>/", Prisme10QBatchView.as_view(), name="batch"),
    path(
        "batch/<int:pk>/download",
        Prisme10QBatchDownloadView.as_view(),
        name="batch-download",
    ),
    path("batch/<int:pk>/send", Prisme10QBatchSendView.as_view(), name="batch-send"),
]

kas/kas/templates/includes/detail_tabs/anvendt_negativt_afkast.html
{% load i18n %}
{% with marked_year=policy.year %}
{% with used_negativ_table=policy.previous_year_deduction_table_data %}
{% with years_with_negative_payout_history=policy.years_with_negative_payout_history %}
{% with years_with_protected_negative_payout=policy.years_with_protected_negative_payout %}
{% with latest_used_negativ_table=policy.latest_policy.previous_year_deduction_table_data %}
<table class="table table-bordered table-hover table-sm autowidth" label="used_negativ_table">
    <thead>
    <tr class="table-info">
        <th colspan="2"></th>
        <th colspan="{{ used_negativ_table|length|add:-1 }}" class="text-center">{% translate 'Anvendt i år' %}</th>
        <th></th>
    </tr>
    <tr>
        <th class="table-info">{% translate 'År' %}</th>
        <th class="table-info">{% translate 'Negativt afkast' %}</th>
        {% for year in used_negativ_table.keys %}
            {% if not forloop.first %}
                <th class="table-{% if marked_year == year %}primary{% else %}info{% endif %}">{{ year }}</th>
            {% endif %}
        {% endfor %}
        <th class="table-info">{% translate 'Resterende' %}</th>
    </tr>
    </thead>
    <tbody>
    {% for year, data in used_negativ_table.items %}
        {% if not forloop.last %}
            <tr>
                <th>{{ year }}</th>
                <td class="text-right">{{ data.available }}</td>
                {% for year2, value in data.used_by_year.items %}
                    {% if not forloop.first %}
                        {% if value == "-" %}
                            <td class="table-secondary"></td>
                        {% else %}
                            <td class="text-right{% if marked_year == year2 %} table-success{% endif %}">

                            {% with limit=latest_used_negativ_table|get:year|get:"used_max_by_year"|get:year2%}
                            {% if  limit > 0 %}
                            <!-- Edit link -->
                            <a href="{% url 'kas:define-negative-policy-payout' pk=policy.pk from=year to=year2 %}?back={{policy.year}}">{{ value }}</a>
                            {% else %}
                            {{ value }}
                            {% endif %}
                            {% endwith %}

                            {% with lookup_tuple=year|make_tuple:year2 %}

                            {% if lookup_tuple in years_with_negative_payout_history %}
                            <!-- History link -->
                            <span class="historylink">
                                <a href="{% url 'kas:define-negative-policy-payout-history' pk=policy.pk from=year to=year2%}?back={{policy.year}}">({% translate 'Historik' %})</a>
                            </span>
                            {% endif %}

                            {% if lookup_tuple in years_with_protected_negative_payout %}
                            <!-- Anchor symbol -->
                            <span class="align-bottom anchor-symbol" data-toggle="tooltip" data-placement="bottom" title="{% translate 'Beskyttet mod genberegninger' %}">&#x2693;</span>
                            {% endif %}

                            {% endwith %}

                            </td>
                        {% endif %}
                    {% endif %}
                {% endfor%}
                <td class="text-right" title="{% blocktranslate with remaining=data.remaining %}Tilgængeligt negativt afkast som kan fordeles: {{remaining}} kr.{% endblocktranslate %}">{{ data.remaining }}</td>
            </tr>
        {% endif %}
    {% endfor %}
    <tr>
        <th colspan="2">{% translate 'Totalt anvendt' %}</th>
        {% for year, data in used_negativ_table.items %}
            {% if not forloop.first %}
                <td
                        class="text-right{% if marked_year == year %} table-success{% endif %}"
                        title="{% blocktranslate with used=data.used_total taxable=data.used_max %}Fradrag fra tidligere års tab: {{used}} kr. Totalt skattepligtigt: {{taxable}} kr.{% endblocktranslate %}"
                >{{ data.used_total }} / {{ data.used_max }}</td>
            {% endif %}
        {% endfor %}
        <td></td>
    </tr>
    </tbody>
</table>
{% endwith %}
{% endwith %}
{% endwith %}
{% endwith %}
{% endwith %}

kas/kas/templates/includes/detail_tabs/attachments.html
{% load i18n %}
<table class="table table-bordered table-sm">
    <thead>
    <tr>
        <th>{% translate 'Uploaded af' %}</th>
        <th>{% translate 'Beskrivelse' %}</th>
        {% if policy_col %}
            <th>{% translate 'Police' %}</th>
        {% endif %}
        <th>{% translate 'Tidspunkt' %}</th>
        <th>{% translate 'Fil' %}</th>
    </tr>
    </thead>
    <tbody>
    {% for attachment in attachments %}
        <tr>
            <td>{{ attachment.uploaded_by|default_if_none:"Borger"  }}</td>
            <td>{{ attachment.description }}</td>
            {% if policy_col  %}
                <td>
                    {% if attachment.policy_tax_year %}
                    <a href="{% url 'kas:policy_detail' attachment.policy_tax_year.pk %}?tab=bilag">{{ attachment.policy_tax_year.policy_number }}</a>
                    {% endif %}
                </td>
            {% endif %}
            <td>{{ attachment.uploaded_at }}</td>
            <td><a href="{% url 'kas:policy_document_download' attachment.id %}">{{ attachment.name }}</a></td>
        </tr>
     {% empty %}
        <tr>
            <td colspan="4">{% translate 'Ingen bilag fundet' %}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

kas/kas/templates/includes/detail_tabs/foreign_notes.html
{% load i18n %}
<p>
    {% translate 'Ingen noter' as empty %}
    {{ person_tax_year.foreign_pension_notes|default:empty }}
</p>

kas/kas/templates/includes/detail_tabs/general_notes.html
{% load i18n %}
<p>
    {% translate 'Ingen noter' as empty %}
    {{ person_tax_year.general_notes|default:empty }}
</p>

kas/kas/templates/includes/detail_tabs/policies_list.html
{% load i18n %}
<table class="table table-bordered table-sm">
    <thead>
    <tr>
        <th>{% translate 'År' %}</th>
        <th>{% translate 'Pensionsselskab' %}</th>
        <th>{% translate 'Police nr.' %}</th>
        <th>{% translate 'Slutlignet' %}</th>
        <th>{% translate 'Kræver efterbehandling' %}</th>
        <th>{% translate 'Næste behandlingsdato'%}</th>
        <th class="text-right">{% translate 'Fortrykt beløb'%}</th>
        <th class="text-right">{% translate 'Admin-ændret R75 beløb'%}</th>
        <th class="text-right">{% translate 'R75 beløb justeret for skattedage'%}</th>
        <th class="text-right">{% translate 'Selvangivet beløb'%}</th>
        <th class="text-right">{% translate 'Ansat beløb'%}</th>
        <th class="text-right">{% translate 'Anvendt beløb'%}</th>
        <th class="text-right">{% translate 'Selvangivet forskel'%}</th>
    </tr>
    </thead>
    <tbody>
    {% for policy in policies %}
        <tr{% if not policy.active %} class="text-muted"{% endif %}>
            <td>{{ policy.person_tax_year.year }}</td>
            <td>{{ policy.pension_company.name }}</td>
            <td><a href="{% url 'kas:policy_detail' policy.pk %}">{{ policy.policy_number }}</a></td>
            <td>{% if policy.slutlignet %}<span>{% translate 'Ja' %}</span>{% else %}<span>{% translate 'Nej' %}</span>{% endif %}</td>
            <td>{% if policy.efterbehandling %}<span>{% translate 'Ja' %}</span>{% else %}<span>{% translate 'Nej' %}</span>{% endif %}</td>
            <td>{{ policy.next_processing_date|date:'SHORT_DATE_FORMAT'|default_if_none:"" }}</td>
            <td class="text-right">{{ policy.prefilled_amount|default_if_none:"" }}</td>
            <td class="text-right">{{ policy.prefilled_amount_edited|default_if_none:"" }}</td>
            <td class="text-right">{{ policy.prefilled_adjusted_amount|default_if_none:"" }}</td>
            <td class="text-right">{{ policy.self_reported_amount|default_if_none:"" }}</td>
            <td class="text-right">{{ policy.assessed_amount|default_if_none:"" }}</td>
            <td class="text-right"><strong>{{ policy.get_base_calculation_amount|default_if_none:"" }}</strong></td>
            <td class="text-right">{% if policy.reported_difference %}{{ policy.reported_difference }} ({{ policy.reported_difference_pct }} %){% endif %}</td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="12">{% translate 'Ingen policer fundet' %}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

kas/kas/templates/includes/detail_tabs/settlements.html
{% load i18n %}
<table class="table table-bordered table-sm">
    <thead>
    <tr>
        <th class="w-10 text-center">{% translate 'Oprettet' %}</th>
        <th class="w-10 text-center">{% translate 'Sendt' %}</th>
        <th class="text-center">{% translate 'Emne i E-boks' %}</th>
        <th class="w-5 text-center">{% translate 'Status' %}</th>
        <th class="w-10 text-center">{% translate 'Afsendelses status' %}</th>
        <th class="w-5 text-center">{% translate 'Prisme 10Q beløb' %}</th>
        <th class="w-25 text-center">{% translate 'Handlinger' %}</th>
    </tr>
    </thead>
    <tbody>
    {% for settlement in settlements %}
        <tr {% if settlement.invalid %} class="text-muted"{% endif %}>
            <td class="text-center">{{ settlement.created_at|date:"SHORT_DATETIME_FORMAT" }}</td>
            <td class="text-center">{{ settlement.send_at|date:"SHORT_DATETIME_FORMAT" }}</td>
            <td>{{ settlement.title }}</td>
            <td class="text-center">{% if settlement.invalid %}{% translate 'Ugyldig'%}{% else %}{{ settlement.get_status_display }}{% endif %}</td>
            <td class="text-center">{{ settlement.delivery_status }}</td>
            <td>
                {% with transaction=settlement.get_transaction %}
                {% if transaction %}
                    <a href="{% url 'prisme:batch' pk=transaction.prisme10q_batch.pk %}">{{ transaction.amount }} ({{ transaction.get_10q_status_display }})</a>
                {% endif %}
                {% endwith %}
            </td>
            <td>
                {% if settlement.pdf %}
                <a class="btn btn-primary" href="{% url 'kas:final_settlement_download' settlement.uuid %}">
                    {% translate 'Vis' %}
                </a>
                {% endif %}
                {% if settlement.pseudo %}
                <a class="btn btn-primary" href="{% url 'kas:update-pseudo-final-settlement' settlement.uuid %}">
                    {% translate 'Upload PDF' %}
                </a>
                {% endif %}
                {% if perms.kas.change_finalsettlement %}
                    <button {% if settlement.invalid or settlement.status != 'created' %}disabled {% endif %} data-url="{% url 'kas:invalid-final-settlement' settlement.uuid %}" type="button" class="btn btn-danger ml-3" data-toggle="modal" data-target="#invalidFinalSettlementModal">
                        {% translate 'Markér som ugyldig' %}
                    </button>
                {% endif %}
                {% if perms.kas.change_finalsettlement and settlement.allow_dispatch is True and settlement.person_tax_year.tax_year.year_part == 'genoptagelsesperiode' %}
                <button {% if settlement.invalid %}disabled {% endif %} data-url="{% url 'kas:dispatch-final-settlement' settlement.uuid %}" type="button" class="btn btn-success ml-3" data-toggle="modal" data-target="#finalSettlementModal">
                    {% translate 'Afsend slutopgørelse' %}
                </button>
                {% endif %}
            </td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="7">{% translate 'Ingen slutopgørelser fundet' %}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>


<div class="modal fade" id="invalidFinalSettlementModal" tabindex="-1" aria-labelledby="invalidFinalSettlementModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="invalidFinalSettlementModalLabel">{% translate 'Markér slutopgørelse som ugyldig' %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {% translate 'Her du sikker du vil markere slutopgørelse som ugyldig?' %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{% translate 'Luk' %}</button>
                <form class="inline" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">{% translate 'Ja' %}</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="finalSettlementModal" tabindex="-1" aria-labelledby="finalSettlementModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="finalSettlementModalLabel">{% if person_tax_year.latest_processing_date %}<i class="fa fa-exclamation-triangle text-danger" aria-hidden="true"></i>{% endif %} {% translate 'Afsend slutopgørelse' %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST">
                {% csrf_token %}
                <div class="modal-body form-row">
                    {% if person_tax_year.latest_processing_date %}
                        <h5 class="modal-title" id="finalSettlementModalLabel">{% blocktrans with date=person_tax_year.latest_processing_date|date:'SHORT_DATE_FORMAT'%} Afsend slutopgørelse og ignorer tidsfristen d.{{ date }}{% endblocktrans %}</h5>
                    {% endif %}
                    <label class="mt-3">{% translate 'Eboks titel' %}</label>
                    <input class="form-control" type="text" name="title" autocomplete="off" required>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{% translate 'Luk' %}</button>
                    <button type="submit" class="btn btn-success">{% translate 'Afsend slutopgørelse' %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script nonce="{{ request.csp_nonce }}">
    $('div.modal').on('show.bs.modal', function (event) {
        //used for both modals
        const button = $(event.relatedTarget);
        const url = button.data('url');
        $(this).find('form').attr('action', url);
    });
</script>

kas/kas/templates/includes/detail_tabs/transactions.html
{% load i18n %}
<table class="table table-bordered table-sm">
    <thead>
    <tr>
        <th>{% translate 'Status' %}</th>
        <th>{% translate 'Type' %}</th>
        <th>{% translate 'Oprettet' %}</th>
        <th>{% translate 'Prisme bunke' %}</th>
        <th>{% translate 'Beløb' %}</th>
    </tr>
    </thead>
    <tbody>
    {% for transaction in transactions %}
        <tr>
            <td>{{ transaction.get_status_display }}</td>
            <td>{{ transaction.get_type_display }}</td>
            <td>{{ transaction.created_at|date:"SHORT_DATETIME_FORMAT" }}</td>
            <td>
                {% if transaction.type == 'prisme10q' and transaction.prisme10q_batch is not None %}
                <a href="{% url 'prisme:batch' pk=transaction.prisme10q_batch.pk %}">{{transaction.prisme10q_batch}}</a>
                {% endif %}
            </td>
            <td>{{ transaction.amount }}</td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="{% if policy_col %}6{% else %}5{% endif %}">{% translate 'Ingen transaktioner fundet' %}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>